### PR TITLE
Initial speaker list addition for Oxidize 1K

### PR DESCRIPTION
**Pull request by jamesmunns**
[Rendered View](https://deploy-preview-30--trusting-allen-741532.netlify.com/oxidize-1k/#speakers-and-schedule)

### CODE REVIEW

**Comment by jamesmunns** [comment]
CC speakers, please let me know if this looks good to you, if so we will publish in a few hours!

* @tarcieri
* @nickray
* @disasm
* @jonathanpallant
* @mrinalwadhwa
* @conorpp
* @Tiwalun
* @bcantrill
* @jordens

**Comment by jonathanpallant** [comment]
LGTM

**Comment by jordens** [comment]
All good!

**Comment by mrinalwadhwa** [comment]
Looks good 👍

**Comment by jamesmunns** [comment]
Merging this, thanks everyone! If you have any requests later, please feel free to open a PR, Issue, or send us an email!

**Pull request merged**
